
name: Terraform-Azure-Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_tenant_id: ${{ secrets.tenant_id }}
      TF_VAR_client_id: ${{ secrets.client_id }}
      TF_VAR_client_secret: ${{ secrets.client_secret }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Stage 1: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Stage 2: Terraform Fmt
      - name: Terraform Format
        run: terraform fmt -check

      # Stage 3: Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Stage 4: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Stage 5: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # Stage 6: Show Outputs
      - name: Terraform Output
        run: terraform output

      # Final Stage: Deployment Confirmation
      - name: Deployment Status
        run: echo "âœ… Your Terraform code is deployed successfully!"
